#!/bin/sh

echo "////    Auto-generated by symbol_gen.sh. DO NOT EDIT!" > __symbols.c
echo "#include \"src/symbols.h\"" >> __symbols.c
echo "const symbol_t __symbol_tab[] = {" >> __symbols.c
nm $1 | grep -i " t " | awk '{ print "    { .addr = (void *)0x"$1", .name = \""$3"\" }," }' | sort >> __symbols.c
echo "    { .addr = (void *)0xffffffffffffffff, .name = \"\" }};" >> __symbols.c
