name: Build and test for compile errors
on:
  push:
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    name: Build components
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install util-linux dosfstools mtools nasm clang build-essential wget

      - name: Build glass
        run: git clone https://github.com/rizet/skylight.git && cd skylight && make glass
    