name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening an issue! Since this is your first time, we would like to thank you for your interaction!'
        pr-message: 'Thank you for your valuable contribution! Please make sure all checks have passed on every commit, and that you have tested your patches.'
